#!/bin/sh

case "$1" in
    lock)
        i3lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        sudo pm-suspend   
        ;;
    reboot)
        sudo reboot
        ;;
    shutdown)
        sudo shutdown -Ph now
        ;;
    *)
        echo "Usage: $0 {lock|logout|sustend|reboot|shutdown}"
        exit 2
esac

exit 0
