#!/bin/sh
lock() {
    i3lock
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    reboot)
        sudo reboot
        ;;
    shutdown)
        sudo shutdown -Ph now
        ;;
    *)
        echo "Usage: $0 {lock|logout|reboot|shutdown}"
        exit 2
esac

exit 0
